### ISSUE TITLE
Report final controls

### ISSUE THREAD

**Issue by vrolnes** [askari12/2I.A-day-in-BIlkent#12]
Report must be controlled before the final submission.

**Comment by kilicaslanalper** [comment]
-introduction must be updated
-story mode must deleted in functional parts
-the word "side kick" must changed to "companion"
-functional req -> highscore depends on normal mode not survival
-no help section in func. req. 
-settings part has to change -> no mouse sensitivity
-every character is unlocked rn also no upgrades-> func. req.
-no graphical smoothness in non func.
-we have to change extendibility in non func
-no fast assets loading
-should add conclusion
-should add glossary
