### ISSUE TITLE
First Report parts

### ISSUE THREAD

**Issue by askari12** [askari12/2I.A-day-in-BIlkent#3]
Everyone Start your Reports in a txt file and upload on the doc folder of Unstable branch.
If there are problems or you want help in anything , start an issue and add us all in the issue so we can have a look at it.
 I will close the Issue when all of you guys comment done ! 😄

**Comment by vrolnes** [comment]
Done!

**Comment by asafkaganbezgin** [comment]
Done

**Comment by askari12** [comment]
Guess everyone did ! Best
