### ISSUE TITLE
Non-Functional Requirements

### ISSUE THREAD

**Issue by vrolnes** [askari12/2I.A-day-in-BIlkent#4]
Guys i added the first draft of non-functional requirements, i would like you to look and tell me if there is something wrong(like grammar mistake or impaired expression) or any part that you found it is not good enough.

If everyboy says it is good i will cloose the issue.

Thanks!

**Comment by askari12** [comment]
Bro , had a suggestion. Should we add "Fast Asset Loading" The game will load all the skins and pictures during the Loading screen so that the rest of the game runs smoothly for the player.

**Comment by askari12** [comment]
Bro it has grammar mistakes in it. I will correct them. Do you think we need to add more data into it ?

**Comment by askari12** [comment]
@enes34bjk I have made some changes. Will do some more in the morning. Please have a look and tell what you think.

**Comment by vrolnes** [comment]
Okay thanks man :) i think that much information is enough 👍

**Comment by vrolnes** [comment]
I fixed the grammar mistakes that i found,can you check again?

**Comment by askari12** [comment]
@enes34bjk Thanks man ! Would be obliged if you could have another look at the grammar. Made another update to the report.

**Comment by vrolnes** [comment]
Done!
