### ISSUE TITLE
Create a Google doc for meeting logs

### ISSUE THREAD

**Issue by ugurdogrusoz** [askari12/2I.A-day-in-BIlkent#6]
and make sure the instructor and the TA has read access to it. Also make sure README.md has a link to it. You will update this doc as you meet.

**Comment by askari12** [comment]
We have one made already Sir. @enes34bjk  Please add Sir to it as well.

**Comment by askari12** [comment]
@ugurdogrusoz , Sir can you please check sir if you can view the document.

**Comment by ugurdogrusoz** [comment]
👍
