### ISSUE TITLE
About Story Mode

### ISSUE THREAD

**Issue by kilicaslanalper** [askari12/2I.A-day-in-BIlkent#8]
Hey guys, 
About story mode, I want to hear your opinions.
First of all, I want to introduce our bosses:
1- Uğur Doğrusöz (CS319)
2- Will Sawyer (CS224)
3- Mehmet Baray (CS223)
4- Özcan Öztürk (CS224)
5- Selim Aksoy (CS484)
6- Halil Altay Güvenir (CS315)
7- Osman Oğuz (IE400)
8- Billur Barshan (EEE391)

I want to use Ercüment Hoca as a helper, because he is more like a student than a teacher.
I showed the courses, TAs will be chosen according to them.
Bosses shoot something related with the course.
Companions are selected according to the course (for example, in cs224 stage, mips green card will be our companion). 
Should we implement gender?
Should we take a name for our character at the beginning of the story mode and use it for the story part of our game?
If you guys have any ideas, feel free to comment and we'll discuss it under this issue.

Have a nice day!

**Comment by vrolnes** [comment]
Looks great :) 
Yeah i think we should add character gender option and story mode speech lines should go according to player's character name choose.

**Comment by kilicaslanalper** [comment]
Moreover, I'm thinking that user must play the Story mode first and then user can unlock the Survival mode. So that the game will be more competitive.

**Comment by vrolnes** [comment]
Sure why not :D

**Comment by askari12** [comment]
Ercument hoca can be a shield for boss bullets

**Comment by askari12** [comment]
No need for gender I think.

Doesnt the player choose the Companions at the start ? I dont get the green card suggestion.. Or in story mode, the companions change per level and in Survival mode, the player can choose ?

I dont think we need to name TAs , I think they can be generic

**Comment by AbdullahWali** [comment]
this sounds like the best CS319 project so far :p

**Comment by kilicaslanalper** [comment]
In story mode, I think player shouldn’t choose the companions. In survival, yes, they can.
